[project]
name = "magistrska"
version = "0.1.0"
description = "Masters - audio continuation"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
  "ipykernel>=7.1.0",
  "ipywidgets>=8.1.8",
  "torch>=2.11.0",
  "torchaudio>=2.11.0",
  "torchcodec>=0.11.0",
  "transformers>=4.57.1",
  "torchinfo>=1.8.0",
  "descript-audio-codec>=1.0.0",
  "tqdm>=4.67.1",
  "nvidia-npp>=13.1.0.44",
  "ffmpeg>=1.4",
  "tensorboard",
]

# CPU only
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pip"
url = "https://pypi.org/simple"
explicit = true

# GPU - NVIDIA
[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

# GPU - ROCm
# [[tool.uv.index]]
# name = "pytorch-gpu"
# url = "https://download.pytorch.org/whl/rocm6.4"
# explicit = true

# [tool.uv.sources]
# torch = [{ index = "pytorch-cpu" }]
# torchvision = [{ index = "pytorch-cpu" }]
# torchaudio = [{ index = "pytorch-cpu" }]
# torchcodec = [{ index = "pytorch-cpu" }]
# ffmpeg = [{ index = "pip" }]





[tool.uv.sources]
torch = [{ index = "pytorch-gpu" }]
torchvision = [{ index = "pytorch-gpu" }]
torchaudio = [{ index = "pytorch-gpu" }]
torchcodec = [{ index = "pytorch-cpu" }]
# ffmpeg = [{ index = "pytorch-gpu" }]

